### ISSUE TITLE
A note on installing and running geneval

### ISSUE THREAD

**Issue by arijit-hub** [djghosh13/geneval#12]
Hi,

A huge thanks to the authors for this amazing work. However, there has been an issue with the installation (#3 #4 #5 ). In this issue I give the step by step installation procedure on how I made everything work. A huge shoutout to @8uos and his amazing issue (#8 ) which helped me a lot in this.

First and foremost, the python version. It is quite important. I used `python 3.8.10` and it worked like charm. So I would advise you on using that. 

Given that you have installed `python 3.8.10` and its alias is `python` I like to use `venv` for my environment creation. You can obviously use conda and do the same exact thing. Activate your environment and do the following things step by step.

1. **Cloning the repository and downloading the ckpt** 
`git clone https://github.com/djghosh13/geneval.git`
`cd geneval` --> `./evaluation/download_models.sh "<OBJECT_DETECTOR_FOLDER>/"` (this downloads the ckpt to `<OBJECT_DETECTOR_FOLDER>/`)

2. **Installing dependencies**
`pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121`
`pip install open-clip-torch==2.26.1`
`pip install clip-benchmark`
`pip install -U openmim`
`pip install einops`
`python -m pip install lightning`
`pip install diffusers["torch"] transformers`
`pip install tomli`
`pip install platformdirs`
`pip install --upgrade setuptools` (You need to have the latest version)

3. **mmengine and mmcv dependency installation** (Should be done after pip installations)
`mim install mmengine mmcv-full==1.7.2`

4. **mmdet installation**
`git clone https://github.com/open-mmlab/mmdetection.git`
`cd mmdetection; git checkout 2.x`
`pip install -v -e .`

At this point every dependency is installed. You can now use the stable diffusion image generation script in `generation/diffuser_generate.py` to generate your images. You can update this script to match your own model.

For completeness; I am gonna paste the remaining steps copied directly from the `README.md`.

5. **Image generation**
```{bash}
python generation/diffusers_generate.py \
    "<PROMPT_FOLDER>/evaluation_metadata.jsonl" \
    --model "runwayml/stable-diffusion-v1-5" \
    --outdir "<IMAGE_FOLDER>"
```

This will result in the generation of images in <IMAGE_FOLDER>.

6. **Evaluation part 1: generation of `results.jsonl` file**
```{bash}
python evaluation/evaluate_images.py \
    "<IMAGE_FOLDER>" \
    --outfile "<RESULTS_FOLDER>/results.jsonl" \
    --model-path "<OBJECT_DETECTOR_FOLDER>"
```

7. **Evaluation part 2: final score **
`python evaluation/summary_scores.py "<RESULTS_FOLDER>/results.jsonl"`

That's it.

I hope this helps out the ones who are facing the installation issue and I hope we all can validate using `geneval`.

**Comment by LaVieEnRoseSMZ** [comment]
Thanks for the update on installing with the new CUDA versions. I followed the instructions and successfully set up the environment, but I'm still encountering an issue with unusual evaluation results. The generated images seem to match the official outputs, yet the evaluation scores are unexpectedly low:

```
python generation/diffusers_generate.py \
    "<PROMPT_FOLDER>/evaluation_metadata.jsonl" \
    --model "stable-diffusion-v1-5/stable-diffusion-v1-5" \
    --outdir "<IMAGE_FOLDER>"
```

However, the evaluation results are as follows:

```
colors           = 6.65% (25 / 376)
counting         = 0.00% (0 / 320)
position         = 0.00% (0 / 400)
color_attr       = 0.00% (0 / 400)
single_object    = 14.37% (46 / 320)
two_object       = 0.00% (0 / 396)
```

Overall score (avg. over tasks): 0.03504

Has anyone encountered this issue before or knows how to fix it?

**Comment by arijit-hub** [comment]
Hi,

I just regenerated and recalculated the scores and they seem to be alright. May I know the steps that you are doing for the evaluation after your images are generated?

**Comment by LaVieEnRoseSMZ** [comment]
I followed steps 5, 6, and 7 and obtained the results I shared earlier. However, when executing step 6, I encountered the following error:

"error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device."

I’m not sure if this is the cause of the issue, but I assume it shouldn’t have a significant impact. Could this be relevant?

**Comment by arijit-hub** [comment]
Hi,

I feel it might have an impact. Can you create a fresh environment and redo the installation step and then retry using this new environment?

**Comment by LaVieEnRoseSMZ** [comment]
I created a fresh environment, redid the installation steps, and reran steps 5, 6, and 7. However, I still encountered the same error and obtained similar results, with lower scores than expected. This could be an effect of the error, but I’m unsure how to resolve it.

**Comment by arijit-hub** [comment]
Hi,

Can you see if your nvidia drivers are up to date on not? Sometimes these issues come with the nvidia drivers being out-dated and updating the drivers can solve the issues. But I am no expert in this. Still may be worth a try?

**Comment by ChenVoid** [comment]
> Hi,
> 
> Can you see if your nvidia drivers are up to date on not? Sometimes these issues come with the nvidia drivers being out-dated and updating the drivers can solve the issues. But I am no expert in this. Still may be worth a try?

Hi, I have met the same issue too. The error is "error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device.", and the resulting score is lower.

**Comment by LaVieEnRoseSMZ** [comment]
https://github.com/open-mmlab/mmdetection/issues/11044 I found this issue, tried the mmcv reinstall solution, but still not working and getting the same error, it might be something related to the H100 GPU

**Comment by arijit-hub** [comment]
Hmm. Can you try installing pytorch using cuda 11.8 and see if it works? `pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118`.

**Comment by LaVieEnRoseSMZ** [comment]
It’s difficult for me to switch to an older CUDA version. However, I resolved the issue by redoing all the steps on an NVIDIA RTX A6000. It seems the problem was related to the Hopper GPU or a newer GPU version.

Thanks again for your notes on the installation with CUDA 12—I really appreciate it!

**Comment by rinongal** [comment]
For anyone with a Hopper GPU that gets here - compiling mmcv yourself should get you the rest of the way. This is instead of `mim install mmcv-full==1.7.2` in step 3.

```
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv; git checkout 1.x
MMCV_WITH_OPS=1 MMCV_CUDA_ARGS="-arch=sm_90" pip install -v -e .
```

You may also need to use `MMCV_CUDA_ARGS="-arch=sm_90"` when compiling mmdet (section 4 in OP).

Make sure your nvcc is for cuda version 12.1 (e.g., `conda install cuda-nvcc -c nvidia/label/cuda-12.1.0`)

**Comment by LaVieEnRoseSMZ** [comment]
It works for me now! Thanks a lot.

**Comment by pkulwj1994** [comment]
This note works. Thanks a lot!

**Comment by stardusts-hj** [comment]
> For anyone with a Hopper GPU that gets here - compiling mmcv yourself should get you the rest of the way. This is instead of `mim install mmcv-full==1.7.2` in step 3.
> 
> ```
> git clone https://github.com/open-mmlab/mmcv.git
> cd mmcv; git checkout 1.x
> MMCV_WITH_OPS=1 MMCV_CUDA_ARGS="-arch=sm_90" pip install -v -e .
> ```
> 
> You may also need to use `MMCV_CUDA_ARGS="-arch=sm_90"` when compiling mmdet (section 4 in OP).
> 
> Make sure your nvcc is for cuda version 12.1 (e.g., `conda install cuda-nvcc -c nvidia/label/cuda-12.1.0`)

So many thanks for your help, I followed your suggestion and run mmcv successfully.

**Comment by mumu-code** [comment]
> 我按照步骤 5、6 和 7 获得了我之前分享的结果。但是，在执行步骤 6 时，我遇到了以下错误：
> 
> “ms_deformable_im2col_cuda错误：没有内核映像可用于在设备上执行。”
> 
> 我不确定这是否是问题的原因，但我认为它应该不会产生重大影响。这有关系吗？



> Thanks for the update on installing with the new CUDA versions. I followed the instructions and successfully set up the environment, but I'm still encountering an issue with unusual evaluation results. The generated images seem to match the official outputs, yet the evaluation scores are unexpectedly low:
> 
> ```
> python generation/diffusers_generate.py \
>     "<PROMPT_FOLDER>/evaluation_metadata.jsonl" \
>     --model "stable-diffusion-v1-5/stable-diffusion-v1-5" \
>     --outdir "<IMAGE_FOLDER>"
> ```
> 
> However, the evaluation results are as follows:
> 
> ```
> colors           = 6.65% (25 / 376)
> counting         = 0.00% (0 / 320)
> position         = 0.00% (0 / 400)
> color_attr       = 0.00% (0 / 400)
> single_object    = 14.37% (46 / 320)
> two_object       = 0.00% (0 / 396)
> ```
> 
> Overall score (avg. over tasks): 0.03504
> 
> Has anyone encountered this issue before or knows how to fix it?

would you please tell how to solve this problem,I meet this problem ,too. the score is Overall score (avg. over tasks): 0.03169

**Comment by arijit-hub** [comment]
Hi @mumu-code ,

Sorry for overlooking the comment. But may I know which gpu are you using? @LaVieEnRoseSMZ was suffering from the same issue because of H100. This can be solved by following this for installation: https://github.com/djghosh13/geneval/issues/12#issuecomment-2789202971

**Comment by mumu-code** [comment]
> Hi [@mumu-code](https://github.com/mumu-code) ,
> 
> Sorry for overlooking the comment. But may I know which gpu are you using? [@LaVieEnRoseSMZ](https://github.com/LaVieEnRoseSMZ) was suffering from the same issue because of H100. This can be solved by following this for installation: [#12 (comment)](https://github.com/djghosh13/geneval/issues/12#issuecomment-2789202971)

thanks

> Hi [@mumu-code](https://github.com/mumu-code) ,
> 
> Sorry for overlooking the comment. But may I know which gpu are you using? [@LaVieEnRoseSMZ](https://github.com/LaVieEnRoseSMZ) was suffering from the same issue because of H100. This can be solved by following this for installation: [#12 (comment)](https://github.com/djghosh13/geneval/issues/12#issuecomment-2789202971)

thank you very much to your sharing!     The issue I raised earlier has been resolved. The problem was caused by loading the wrong config file when using the configuration, which resulted in some model parameters not being loaded properly. I think  this led to the inaccuracies in the detection model. After correcting the config file, this issue was resolved

**Comment by yuanzhi-zhu** [comment]
I got a weird error
`ERROR: No matching distribution found for setuptools>=40.8.0`
turned out this can be fixed by downgrading to setuptools==53.0.0

**Comment by yuanzhi-zhu** [comment]
```
pip uninstall -y opencv-python opencv-python-headless
pip install opencv-python opencv-python-headless
```
also do this when I got some numpy error when I run `MMCV_WITH_OPS=1 MMCV_CUDA_ARGS="-arch=sm_90" pip install -v -e .`

**Comment by JARVVVIS** [comment]
Hi, thanks for the awesome notes. Unfortunately, I am still facing this error when I try to run the evaluation script. Any tips on how to fix this?
```
...
    output = MultiScaleDeformableAttnFunction.apply(
  File "/envs/geneval_env/lib/python3.8/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(args, **kwargs)  # type: ignore[misc]
  File "/envs/geneval_env/lib/python3.8/site-packages/mmcv/ops/multi_scale_deform_attn.py", line 65, in forward
    output = ext_module.ms_deform_attn_forward(
RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found.
```

**Comment by arijit-hub** [comment]
Hi @yuanzhi-zhu , 
Thanks for reporting the weird error. I dont know why the error persists like that but I guess its one of those errors related to the hopper gpus, so I wont be surprised. Good that it worked out.

Hi @JARVVVIS ,
I have not gotten such an error message. But I am guessing that it might be because of the gpu you are using. Are you using any of the newer hopper gpus? If yes, please replace step 3 with the comments from @rinongal : https://github.com/djghosh13/geneval/issues/12#issuecomment-2789202971.

Hope this helps.

**Comment by Yupsed** [comment]
Thanks for the wonderful notes!

**Comment by HalvesChen** [comment]
@arijit-hub  Hi! Thanks for your notes! But when I run the command `pip install clip-benchmark`, I meet the error `Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.9; 0.1.1 Requires-Python >=3.9; 0.1.2 Requires-Python >=3.9;`. It seems `python-3.8.10`. Does this seem to be due to a Python version issue? Are you encountering this problem again?

**Comment by Kaiwen-Zhu** [comment]
@HalvesChen I encountered the same issue, and it works for me to `pip install tokenizers==0.20.3` beforehand.

**Comment by 2JAE22** [comment]
this note should be uploaded officialy !! thank you very much ❤️

**Comment by Corleone-Huang** [comment]
Hi, during the execution of the command pip install -v -e . in Step 4, the process hangs indefinitely with no visible progress.

``
Running setup.py develop for mmdet
    Running command python setup.py develop
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /home/tiger/anaconda3/envs/geneval/lib/python3.8/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    /home/tiger/anaconda3/envs/geneval/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    warning: no files found matching 'mmdet/VERSION'
    warning: no files found matching 'mmdet/.mim/demo/*/*'
    adding license file 'LICENSE'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
``
How long would this process takes?

**Comment by Xiepengyu2004** [comment]
Hi, thanks for your guide.
I found something wrong during my environment setup.

1. `pip install --upgrade setuptools` would cause dependency issue.

However, If I ignore this action , my Evaluation Part still works.
So I am wondering if this action is absolutely essential.

2. I would recommend skipping the Image generation part,due to the runtime conflict between the latest diffusers and the older version of torch.

We could run `diffusers_generate.py` in a separate environment with the latest versions of torch and diffusers.

**Comment by a-little-hoof** [comment]
> Hi, thanks for the awesome notes. Unfortunately, I am still facing this error when I try to run the evaluation script. Any tips on how to fix this?
> 
> ```
> ...
>     output = MultiScaleDeformableAttnFunction.apply(
>   File "/envs/geneval_env/lib/python3.8/site-packages/torch/autograd/function.py", line 539, in apply
>     return super().apply(args, **kwargs)  # type: ignore[misc]
>   File "/envs/geneval_env/lib/python3.8/site-packages/mmcv/ops/multi_scale_deform_attn.py", line 65, in forward
>     output = ext_module.ms_deform_attn_forward(
> RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found.
> ```

Hi, I encountered the same error and would like to share my experience. After chatting with GPT, I identify the cause of this problem is compiling only the CPU-version operator during installing. Installing nvcc and cuda toolkit 12.1 can fix it in my case.
```bash
conda install -y -c nvidia cuda-toolkit=12.1
conda install -y -c nvidia/label/cuda-12.1.0 cuda-cccl
```

**Comment by Laksh-Mendpara** [comment]
> Hi, during the execution of the command pip install -v -e . in Step 4, the process hangs indefinitely with no visible progress.
> 
> `` Running setup.py develop for mmdet Running command python setup.py develop running develop running egg_info writing mmdet.egg-info/PKG-INFO writing dependency_links to mmdet.egg-info/dependency_links.txt writing requirements to mmdet.egg-info/requires.txt writing top-level names to mmdet.egg-info/top_level.txt reading manifest file 'mmdet.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' /home/tiger/anaconda3/envs/geneval/lib/python3.8/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated. !!
> 
> ```
>         ********************************************************************************
>         Please avoid running ``setup.py`` and ``easy_install``.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://github.com/pypa/setuptools/issues/917 for details.
>         ********************************************************************************
> 
> !!
>   easy_install.initialize_options(self)
> /home/tiger/anaconda3/envs/geneval/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
> !!
> 
>         ********************************************************************************
>         Please avoid running ``setup.py`` directly.
>         Instead, use pypa/build, pypa/installer or other
>         standards-based tools.
> 
>         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>         ********************************************************************************
> 
> !!
>   self.initialize_options()
> warning: no files found matching 'mmdet/VERSION'
> warning: no files found matching 'mmdet/.mim/demo/*/*'
> adding license file 'LICENSE'
> writing manifest file 'mmdet.egg-info/SOURCES.txt'
> ```
> 
> `` How long would this process takes?

for me it took around 5-8 minutes.

**Comment by PeterL1n** [comment]
What worked for me.

```
python3 -m pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
python3 -m pip install networkx==2.8.8
python3 -m pip install open-clip-torch==2.26.1
python3 -m pip install clip-benchmark
python3 -m pip install -U openmim
python3 -m pip install einops
python3 -m pip install lightning
python3 -m pip install diffusers transformers
python3 -m pip install tomli
python3 -m pip install platformdirs
python3 -m pip install --upgrade setuptools

sudo apt update
sudo apt install libgl1

pip uninstall -y numpy
pip install "numpy<2"

python -m ensurepip --upgrade
python -m pip install --upgrade pip setuptools wheel

git clone https://github.com/open-mmlab/mmcv.git
cd mmcv; git checkout 1.x
MMCV_WITH_OPS=1 MMCV_CUDA_ARGS="-arch=sm_90" python3 -m pip install -v -e . --no-build-isolation
```
